use std::path::{Path, PathBuf};

use chrono::Utc;
use tokio::fs;

use crate::models::SpaceWeatherAlert;

pub async fn generate_alert_report(
    alert: &SpaceWeatherAlert,
    reports_dir: &Path,
) -> std::io::Result<PathBuf> {
    fs::create_dir_all(reports_dir).await?;

    let safe_event_id = sanitize_report_id(&alert.normalized_event_id());
    let report_path = reports_dir.join(format!("ALERT_{safe_event_id}.txt"));
    let dispatch_timestamp = Utc::now();
    let risk_details = format_risk_details(alert);

    let report_body = format!(
        "\
GEOSTORM-AI RISK DISPATCH REPORT
=================================

	Activity ID: {activity_id}
	Event ID: {event_id}
	Schema Version: {schema_version}
	Canonical Alert Level: {alert_level}
{risk_details}
Event Timestamp: {event_timestamp}
Dispatch Timestamp: {dispatch_timestamp}

Alert Details
-------------
{details}

Operational Risk Summary
------------------------
This is a text dispatch artifact generated by
geostorm-alert-service. Treat the incoming anomaly as requiring analyst review,
satellite operations coordination, and downstream notification readiness.

	Email Status: DISABLED_BY_DEFAULT
	",
        event_id = alert.normalized_event_id(),
        schema_version = alert.normalized_schema_version(),
        activity_id = alert.activity_id,
        alert_level = alert.alert_level,
        risk_details = risk_details,
        event_timestamp = alert.timestamp.to_rfc3339(),
        dispatch_timestamp = dispatch_timestamp.to_rfc3339(),
        details = alert.details
    );

    fs::write(&report_path, report_body).await?;

    println!(
        "[report] Compiled text report artifact at {}",
        report_path.display()
    );
    println!(
        "[dispatch] Email disabled by default for activity_id={} alert_level={}",
        alert.activity_id, alert.alert_level
    );

    Ok(report_path)
}

fn format_risk_details(alert: &SpaceWeatherAlert) -> String {
    let mut lines = Vec::new();

    if let Some(current_risk_level) = alert.current_risk_level() {
        lines.push(format!("\tCurrent Observed Level: {current_risk_level}"));
    }

    if let Some(forecast_risk_level) = alert.forecast_risk_level() {
        lines.push(format!("\tForecast Level: {forecast_risk_level}"));
    }

    if let Some(risk_basis) = alert.risk_basis() {
        lines.push(format!("\tRisk Basis: {risk_basis}"));
    }

    lines.join("\n")
}

fn sanitize_report_id(report_id: &str) -> String {
    let sanitized: String = report_id
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' {
                ch
            } else {
                '_'
            }
        })
        .collect();

    if sanitized.is_empty() {
        "UNKNOWN".to_string()
    } else {
        sanitized
    }
}

#[cfg(test)]
mod tests {
    use super::sanitize_report_id;

    #[test]
    fn sanitizes_report_id_for_report_filename() {
        assert_eq!(sanitize_report_id("GST-2026/05/31 A"), "GST-2026_05_31_A");
    }

    #[test]
    fn uses_unknown_for_empty_report_id() {
        assert_eq!(sanitize_report_id(""), "UNKNOWN");
    }
}
