use std::path::{Path, PathBuf};

use chrono::Utc;
use tokio::fs;

use crate::models::SpaceWeatherAlert;

pub async fn generate_alert_report(
    alert: &SpaceWeatherAlert,
    reports_dir: &Path,
) -> std::io::Result<PathBuf> {
    fs::create_dir_all(reports_dir).await?;

    let safe_activity_id = sanitize_activity_id(&alert.activity_id);
    let report_path = reports_dir.join(format!("ALERT_{safe_activity_id}.txt"));
    let dispatch_timestamp = Utc::now();

    let report_body = format!(
        "\
GEOSTORM-AI CRITICAL RISK DISPATCH REPORT
==========================================

Activity ID: {activity_id}
Alert Level: {alert_level}
Event Timestamp: {event_timestamp}
Dispatch Timestamp: {dispatch_timestamp}

Alert Details
-------------
{details}

Operational Risk Summary
------------------------
This is a placeholder PDF-equivalent dispatch artifact generated by
geostorm-alert-service. Treat the incoming anomaly as requiring analyst review,
satellite operations coordination, and downstream notification readiness.

Dispatch Status: MOCK_SMTP_TRIGGERED
",
        activity_id = alert.activity_id,
        alert_level = alert.alert_level,
        event_timestamp = alert.timestamp.to_rfc3339(),
        dispatch_timestamp = dispatch_timestamp.to_rfc3339(),
        details = alert.details
    );

    fs::write(&report_path, report_body).await?;

    println!(
        "[report] Compiled mock PDF report at {}",
        report_path.display()
    );
    println!(
        "[dispatch] MOCK SMTP trigger queued for activity_id={} alert_level={}",
        alert.activity_id, alert.alert_level
    );

    Ok(report_path)
}

fn sanitize_activity_id(activity_id: &str) -> String {
    let sanitized: String = activity_id
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' {
                ch
            } else {
                '_'
            }
        })
        .collect();

    if sanitized.is_empty() {
        "UNKNOWN".to_string()
    } else {
        sanitized
    }
}

#[cfg(test)]
mod tests {
    use super::sanitize_activity_id;

    #[test]
    fn sanitizes_activity_id_for_report_filename() {
        assert_eq!(sanitize_activity_id("GST-2026/05/31 A"), "GST-2026_05_31_A");
    }

    #[test]
    fn uses_unknown_for_empty_activity_id() {
        assert_eq!(sanitize_activity_id(""), "UNKNOWN");
    }
}
